# This file describes an application. You can have multiple applications
# in the same project.

# The name of this app. Must be unique within a project.
name: php

# The toolstack used to build the application.
type: php:7.0
build:
    flavor: symfony

# The relationships of the application with services or other applications.
# The left-hand side is the name of the relationship as it will be exposed
# to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
# side is in the form `<service name>:<endpoint name>`.
#relationships:
#    database: "mysql:mysql"

# The configuration of app when it is exposed to the web.
web:
    # The public directory of the app, relative to its root.
    document_root: "/web"
    # The front-controller script to send non-static requests to.
    passthru: "/app.php"
    whitelist:
      # slides
      - ^/slides/.*\.html$

      # CSS, JavaScript and Other assets.
      - \.css$
      - \.js$
      - ^/assets/
      - ^/bundles/

      # image/* types.
      - \.gif$
      - \.jpe?g$
      - \.png$
      - \.ico
      - \.svg$

      # robots.txt.
      - /robots\.txt$

crons:
    reset:
        # reset the demo every night to avoid overflowing disks and data leftovers
        spec: 30 2 * * *
        cmd: 'bin/console cache:clear --env=prod && bin/console doctrine:phpcr:init:dbal --drop --force -n && bin/console doctrine:phpcr:repository:init -n && bin/console doctrine:phpcr:fixtures:load -n && bin/console --env=prod cache:warmup -n --no-debug'

# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/var/cache": "shared:files/cache"
    "/var/logs": "shared:files/logs"

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
      rm web/app_dev.php
      # place sqlite file into /tmp so that we can write to it during deploy
      sed -i 's@%kernel.root_dir%/../var/app.sqlite@/tmp/app.sqlite@' app/config/parameters.yml
      bin/console --env=prod assets:install -n --no-debug
      bin/console --env=prod assetic:dump -n --no-debug
    deploy: |
      # force clearing the cache
      rm -rf var/cache
      bin/console doctrine:phpcr:init:dbal --drop --force -n
      bin/console doctrine:phpcr:repository:init -n
      bin/console doctrine:phpcr:fixtures:load -n
      bin/console --env=prod cache:warmup -n --no-debug

runtime:
  extensions:
    - name: blackfire
      configuration:
        server_id: "ce95eba9-2d90-48b7-ad75-fcad42e1bcab"
        server_token: "ca7e32ac2d466ecfdf30b8ac43bdfef1304fc3feeb66e8906c1192b435e206f0"
