language: php

php:
  - 5.6
  - 7.0
  # 7.1 is tested using composer install

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: TRANSPORT=jackrabbit COMPOSER_INSTALL=1
    - php: 7.1
      env: TRANSPORT=doctrine_dbal COMPOSER_INSTALL=1
    - php: hhvm
      dist: trusty

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
  matrix:
    - TRANSPORT=jackrabbit
    - TRANSPORT=doctrine_dbal

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    # hack to avoid segmentation fault because of https://bugs.php.net/bug.php?id=74843
  - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then echo "zend.enable_gc = 0" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install: if [ "$COMPOSER_INSTALL" != "1" ]; then composer update --no-scripts --prefer-dist; else composer install --no-scripts --prefer-dist; fi

before_script:
  - cp app/config/phpcr_${TRANSPORT}.yml.dist app/config/phpcr.yml
  - composer run-script post-update-cmd
  - ./tests/travis_${TRANSPORT}.sh
  - bin/console doctrine:phpcr:workspace:create sandbox_test -e=test
  - bin/console doctrine:phpcr:repository:init -e=test

script: vendor/bin/simple-phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
